### ISSUE TITLE
Explanation for displacement factor

### ISSUE THREAD

**Issue by Meghal17** [viplix3/The-Ancient-Secrets-of-Computer-Vision-Assignments#1]
Hi, in week 1 homework in the interpolation function, you have mentioned that we need to take into account the fact that pixel at (-0.5,-0.5) instead of 0,0. Can you explain why at (-0.5,-0.5)?

**Comment by viplix3** [comment]
Hi @Meghal17, for explaining this, let's take a 4x4x3 image as an example.

A 4x4x3 image consists of 4x4 grids of pixels, each grid is of 1x1 unit.
Our understanding of a pixel is that the whole 1x1 unit is a pixel, but this isn't what a pixel actually is!

What (0, 0) coordinate actually depicts is the location of the pixel, which is at the center of the top-left 1x1 unit and not the whole top-left 1x1 unit.
Hence, the (0, 0) coordinate is the coordinate of the pixel at the top-left corner and not the top-left corner of the image. 
The top-left corner of the actual image is at (-0.5, -0.5). Yes, the actual top-left corner of the image runs off of the coordinate system a bit.

Please go through [this snippet of YouTube video](https://youtu.be/5xdbJ7z4Nrc?t=499) lecture by Joseph Redmon. It is explained much better there.
